[package]
name = "num-hyperdual"
version = "0.1.0"
authors = ["Gernot Bauer <bauer@itt.uni-stuttgart.de>",
           "Philipp Rehner <rehner@itt.uni-stuttgart.de>"]
edition = "2018"

[dependencies]
ndarray = "0.13"
num-integer = "0.1"
smallvec = "1.4"
num-traits = {version = "0.2", default-features = false}

[features]
default = ["std"]
std = ["num-traits/std"]
libm = ["num-traits/libm"]
